# Generated by Django 5.0.4 on 2024-11-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_name', models.CharField(help_text='Required - e.g., Standard Delivery or Express Delivery e.t.c.', max_length=255)),
                ('within_city_dc', models.DecimalField(decimal_places=2, help_text='Price must be between 0 and 999.99', max_digits=5, verbose_name='Within City Delivery Charges')),
                ('other_city_dc', models.DecimalField(decimal_places=2, help_text='Price must be between 0 and 999.99', max_digits=5, verbose_name='Other Cities Delivery Charges')),
                ('delivery_timeframe', models.CharField(help_text="Required - e.g., '3-4 days'", max_length=255, verbose_name='Delivery Time-Frame')),
                ('delivery_window', models.CharField(help_text="Required - e.g., '9:00am - 5:00pm'", max_length=255, verbose_name='Delivery Window')),
                ('order', models.IntegerField(default=0, help_text='Required - Order number of which it should be displayed in delivery option list on checkout page', verbose_name='Delivery Option Order Number')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Delivery Option',
                'verbose_name_plural': 'Delivery Options',
                'ordering': ('order',),
            },
        ),
    ]
