# Generated by Django 5.0.4 on 2024-11-18 13:59

import django.db.models.deletion
import django_countries.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=150, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('address_line_1', models.CharField(max_length=150, verbose_name='Address Line 1')),
                ('address_line_2', models.CharField(blank=True, max_length=150, verbose_name='Address Line 2')),
                ('city', models.CharField(choices=[('', 'City'), ('abd', 'Attock'), ('abt', 'Abbottabad'), ('bhr', 'Bahawalnagar'), ('bwn', 'Bhawana'), ('bhk', 'Bhakkar'), ('bwp', 'Bahawalpur'), ('cwp', 'Chishtian'), ('dgh', 'Dera Ghazi Khan'), ('dnb', 'Dinawali'), ('dip', 'Dipalpur'), ('fdr', 'Fateh Jhang'), ('fsl', 'Faisalabad'), ('ghk', 'Gujar Khan'), ('gjr', 'Gujranwala'), ('grk', 'Gwadar'), ('grw', 'Gujranwala'), ('gjr', 'Gujrat'), ('hyd', 'Hyderabad'), ('isl', 'Islamabad'), ('jlm', 'Jalalpur'), ('jwn', 'Jaranwala'), ('jwp', 'Jhelum'), ('khr', 'Khairpur'), ('khi', 'Karachi'), ('khr', 'Khanewal'), ('ktt', 'Kotli'), ('kwb', 'Kot Adu'), ('lai', 'Lalamusa'), ('lhr', 'Lahore'), ('ldr', 'Lodhran'), ('lrd', 'Larkana'), ('ltr', 'Layyah'), ('mll', 'Mian Channu'), ('mlk', 'Malakwal'), ('mlt', 'Mardan'), ('mrd', 'Multan'), ('mnt', 'Mansehra'), ('mgw', 'Mandi Bahauddin'), ('mwm', 'Mianwali'), ('mtr', 'Multan'), ('mzt', 'Murree'), ('mzw', 'Muzaffargarh'), ('ngt', 'Narowal'), ('nwn', 'Nankana Sahib'), ('pwp', 'Peshawar'), ('phl', 'Pattoki'), ('qta', 'Quetta'), ('qrb', 'Quetta Residency'), ('rch', 'Rajanpur'), ('rnw', 'Rawalpindi'), ('rkn', 'Rahim Yar Khan'), ('rwp', 'Rawalpindi'), ('sgr', 'Sargodha'), ('skt', 'Sialkot'), ('shw', 'Sheikhupura'), ('swn', 'Swat'), ('sak', 'Sargodha'), ('sbq', 'Sahiwal'), ('ska', 'Sakrand'), ('skz', 'Sukheki'), ('stw', 'Sialkot'), ('suk', 'Sukkur'), ('swl', 'Sahiwal'), ('sgr', 'Sargodha'), ('swl', 'Sialkot'), ('saw', 'Sawat'), ('ttn', 'Toba Tek Singh'), ('vhn', 'Vehari'), ('wah', 'Wah Cantt'), ('wln', 'Wazirabad')], max_length=150, verbose_name='City')),
                ('state', models.CharField(max_length=150, verbose_name='State/Province')),
                ('country', django_countries.fields.CountryField(default='PK', max_length=2, verbose_name='Country')),
                ('zip_code', models.CharField(max_length=12, verbose_name='Zip Code')),
                ('default', models.BooleanField(default=False, verbose_name='Default')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Billing Address',
                'verbose_name_plural': 'Billing Addresses',
            },
        ),
    ]
