# Generated by Django 5.0.4 on 2024-11-18 13:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(help_text="Promotion name like 'Holiday Sale'.", max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Discount value (amount or percentage).', max_digits=10)),
                ('start_date', models.DateTimeField(help_text='Promotion start date and time.')),
                ('end_date', models.DateTimeField(help_text='Promotion end date and time.')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromotionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.IntegerField(default=1, help_text='Minimum quantity for promotion')),
            ],
        ),
        migrations.CreateModel(
            name='PromoType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Coupon code like 'SUMMER20'.", max_length=50, unique=True)),
                ('expiration_date', models.DateTimeField(blank=True, help_text='Coupon expiration date.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user_restricted', models.ManyToManyField(blank=True, help_text='If restricted to certain users.', related_name='coupons', to=settings.AUTH_USER_MODEL)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='promotion.promotion')),
            ],
        ),
    ]
