# Generated by Django 5.0.4 on 2024-11-18 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('promotion', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
        migrations.AddField(
            model_name='promotionproduct',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotion.promotion'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='promo_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotion.promotype'),
        ),
        migrations.AlterUniqueTogether(
            name='promotionproduct',
            unique_together={('promotion', 'product')},
        ),
    ]
